---
# See https://github.com/jvautier/project-cli
fullname: jvautier/ansible-role-docker-ce
description: Install docker-ce through ansible
tags:
  - ansible
  - ansible-role
  - docker-ce
github:
  has_issues: true
  has_projects: false
  has_wiki: false
