---
- name: Install docker-compose
  when: docker_compose_version is defined
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0777
    force: true
    timeout: 5
